
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Compilar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LISTA = 25;
  public static final int CONTINUAR = 17;
  public static final int MENSAJE = 23;
  public static final int VERDADERO = 73;
  public static final int DIVI = 42;
  public static final int SI = 7;
  public static final int MAYIG = 47;
  public static final int KEEP = 4;
  public static final int BOOLEANSTR = 33;
  public static final int RANDOM = 27;
  public static final int FALSO = 74;
  public static final int CARACTERSTR = 34;
  public static final int NUMERO = 72;
  public static final int PISTAS = 29;
  public static final int OPELV = 44;
  public static final int PISTA = 2;
  public static final int LONGITUD = 22;
  public static final int CIRCULAR = 28;
  public static final int NOR = 53;
  public static final int VAR = 5;
  public static final int PARI = 58;
  public static final int OPINCR = 36;
  public static final int COMENT = 12;
  public static final int PARD = 59;
  public static final int SALIR = 30;
  public static final int HACER = 16;
  public static final int PARA = 14;
  public static final int COMA = 66;
  public static final int DOBIGUAL = 45;
  public static final int IGUAL = 67;
  public static final int OPNOT = 57;
  public static final int NOMBRE = 26;
  public static final int ENTEROSTR = 31;
  public static final int OPDECR = 37;
  public static final int SWITCH = 10;
  public static final int MAY = 50;
  public static final int MULT = 41;
  public static final int NOTA = 75;
  public static final int DIFERENC = 46;
  public static final int OPMOD = 43;
  public static final int MENIG = 48;
  public static final int ARREGLO = 6;
  public static final int EOF = 0;
  public static final int MIENTRAS = 15;
  public static final int DEFAULT = 13;
  public static final int SUMA = 39;
  public static final int OPSUMSIM = 38;
  public static final int SUMARIZAR = 21;
  public static final int CARACTER = 71;
  public static final int CADENASTR = 35;
  public static final int PRINCIPAL = 24;
  public static final int OR = 56;
  public static final int IDENT = 68;
  public static final int error = 1;
  public static final int REPRODUCIR = 19;
  public static final int RESTA = 40;
  public static final int ID = 69;
  public static final int DOBLESTR = 32;
  public static final int SINO = 8;
  public static final int EXTIENDE = 3;
  public static final int CASO = 11;
  public static final int ESPERAR = 20;
  public static final int OPNULO = 49;
  public static final int DOSPUNT = 64;
  public static final int RETORNA = 18;
  public static final int CURLBRACKI = 62;
  public static final int SINOSI = 9;
  public static final int CURLBRACKD = 63;
  public static final int CADENA = 70;
  public static final int PUNTCOMA = 65;
  public static final int AND = 55;
  public static final int BRACKI = 60;
  public static final int MEN = 51;
  public static final int BRACKD = 61;
  public static final int NAND = 52;
  public static final int XOR = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PISTA",
  "EXTIENDE",
  "KEEP",
  "VAR",
  "ARREGLO",
  "SI",
  "SINO",
  "SINOSI",
  "SWITCH",
  "CASO",
  "COMENT",
  "DEFAULT",
  "PARA",
  "MIENTRAS",
  "HACER",
  "CONTINUAR",
  "RETORNA",
  "REPRODUCIR",
  "ESPERAR",
  "SUMARIZAR",
  "LONGITUD",
  "MENSAJE",
  "PRINCIPAL",
  "LISTA",
  "NOMBRE",
  "RANDOM",
  "CIRCULAR",
  "PISTAS",
  "SALIR",
  "ENTEROSTR",
  "DOBLESTR",
  "BOOLEANSTR",
  "CARACTERSTR",
  "CADENASTR",
  "OPINCR",
  "OPDECR",
  "OPSUMSIM",
  "SUMA",
  "RESTA",
  "MULT",
  "DIVI",
  "OPMOD",
  "OPELV",
  "DOBIGUAL",
  "DIFERENC",
  "MAYIG",
  "MENIG",
  "OPNULO",
  "MAY",
  "MEN",
  "NAND",
  "NOR",
  "XOR",
  "AND",
  "OR",
  "OPNOT",
  "PARI",
  "PARD",
  "BRACKI",
  "BRACKD",
  "CURLBRACKI",
  "CURLBRACKD",
  "DOSPUNT",
  "PUNTCOMA",
  "COMA",
  "IGUAL",
  "IDENT",
  "ID",
  "CADENA",
  "CARACTER",
  "NUMERO",
  "VERDADERO",
  "FALSO",
  "NOTA"
  };
}

