
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Comunicacion;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESPUESTA = 19;
  public static final int DURACION = 15;
  public static final int CADENA = 23;
  public static final int IGUAL = 4;
  public static final int DATOS = 22;
  public static final int OCTAVA = 20;
  public static final int BARRA = 5;
  public static final int PISTA = 7;
  public static final int NUMEROSTR = 17;
  public static final int LISTAS = 9;
  public static final int MEN = 3;
  public static final int TIPO = 11;
  public static final int NOTA = 21;
  public static final int NOMBRE = 12;
  public static final int EOF = 0;
  public static final int CANAL = 16;
  public static final int NUMERO = 24;
  public static final int error = 1;
  public static final int FRECUENCIA = 18;
  public static final int MAY = 2;
  public static final int PISTAS = 8;
  public static final int LISTA = 6;
  public static final int SOLICITUD = 10;
  public static final int ALEATORIA = 13;
  public static final int PISTANUEVA = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAY",
  "MEN",
  "IGUAL",
  "BARRA",
  "LISTA",
  "PISTA",
  "PISTAS",
  "LISTAS",
  "SOLICITUD",
  "TIPO",
  "NOMBRE",
  "ALEATORIA",
  "PISTANUEVA",
  "DURACION",
  "CANAL",
  "NUMEROSTR",
  "FRECUENCIA",
  "RESPUESTA",
  "OCTAVA",
  "NOTA",
  "DATOS",
  "CADENA",
  "NUMERO"
  };
}

