
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.ValExpr;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 35;
  public static final int CURLBRACKI = 27;
  public static final int MULT = 6;
  public static final int OPDECR = 3;
  public static final int OPINCR = 2;
  public static final int CURLBRACKD = 28;
  public static final int XOR = 19;
  public static final int RESTA = 5;
  public static final int DIFERENC = 11;
  public static final int BRACKI = 25;
  public static final int PUNTCOMA = 30;
  public static final int AND = 20;
  public static final int IGUAL = 32;
  public static final int NAND = 17;
  public static final int NOR = 18;
  public static final int BRACKD = 26;
  public static final int CARACTER = 34;
  public static final int OR = 21;
  public static final int SUMA = 4;
  public static final int OPNULO = 14;
  public static final int EOF = 0;
  public static final int OPNOT = 22;
  public static final int OPELV = 9;
  public static final int error = 1;
  public static final int NULO = 38;
  public static final int COMA = 31;
  public static final int CADENA = 33;
  public static final int DIVI = 7;
  public static final int MENIG = 13;
  public static final int MAYIG = 12;
  public static final int MEN = 16;
  public static final int PARI = 23;
  public static final int FALSO = 37;
  public static final int OPMOD = 8;
  public static final int PARD = 24;
  public static final int VERDADERO = 36;
  public static final int DOBIGUAL = 10;
  public static final int DOSPUNT = 29;
  public static final int MAY = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPINCR",
  "OPDECR",
  "SUMA",
  "RESTA",
  "MULT",
  "DIVI",
  "OPMOD",
  "OPELV",
  "DOBIGUAL",
  "DIFERENC",
  "MAYIG",
  "MENIG",
  "OPNULO",
  "MAY",
  "MEN",
  "NAND",
  "NOR",
  "XOR",
  "AND",
  "OR",
  "OPNOT",
  "PARI",
  "PARD",
  "BRACKI",
  "BRACKD",
  "CURLBRACKI",
  "CURLBRACKD",
  "DOSPUNT",
  "PUNTCOMA",
  "COMA",
  "IGUAL",
  "CADENA",
  "CARACTER",
  "NUMERO",
  "VERDADERO",
  "FALSO",
  "NULO"
  };
}

