// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: LexerCompilar.jflex

package Analizadores.Compilar;
import java_cup.runtime.*; 
import Analizadores.Compilar.sym.*;
import java.util.List;
import java.util.ArrayList;
import Analizadores.ErrorCom;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class LexerCompilar implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\2\22\0\1\3\1\4"+
    "\1\5\1\6\1\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\12\22\1\23"+
    "\1\24\1\25\1\26\1\27\2\0\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\2\36\1\40\1\41"+
    "\1\42\1\43\1\36\1\44\1\36\1\45\1\46\1\47"+
    "\1\36\1\50\4\36\1\51\1\52\1\53\1\54\1\36"+
    "\1\0\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\40\1\67\1\70\1\71\1\72"+
    "\1\73\1\36\1\74\1\75\1\76\1\77\1\50\1\100"+
    "\1\101\1\36\1\102\1\103\1\104\1\105\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\21\22\1\23\1\24\1\25"+
    "\6\22\1\26\1\1\1\27\1\30\1\0\1\31\2\0"+
    "\1\32\1\33\1\34\2\0\1\35\1\36\1\37\2\0"+
    "\1\40\1\41\1\42\1\43\30\22\1\44\5\22\5\45"+
    "\1\22\1\46\1\47\1\50\1\51\1\14\1\0\37\22"+
    "\1\52\1\22\1\45\1\14\1\43\4\22\1\53\11\22"+
    "\1\54\5\22\1\55\6\22\1\56\2\22\1\57\1\22"+
    "\1\14\7\22\1\60\3\22\1\61\1\62\1\63\4\22"+
    "\1\64\4\22\1\65\1\0\3\22\1\14\2\22\1\66"+
    "\4\22\1\67\5\22\1\70\1\71\1\22\1\72\2\22"+
    "\1\0\1\22\1\73\1\22\1\14\1\74\1\75\3\22"+
    "\1\76\1\77\2\22\1\100\3\22\1\101\1\102\2\22"+
    "\1\14\1\103\1\104\1\22\1\105\1\106\1\107\4\22"+
    "\1\110\1\111\1\22\1\112\1\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[266];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\322\0\u0118\0\106\0\u015e\0\u01a4"+
    "\0\106\0\106\0\106\0\u01ea\0\106\0\u0230\0\106\0\u0276"+
    "\0\106\0\106\0\u02bc\0\u0302\0\u0348\0\u038e\0\u03d4\0\u041a"+
    "\0\u0460\0\u04a6\0\u04ec\0\u0532\0\u0578\0\u05be\0\u0604\0\u064a"+
    "\0\u0690\0\u06d6\0\u071c\0\u0762\0\u07a8\0\u07ee\0\106\0\106"+
    "\0\106\0\u0834\0\u087a\0\u08c0\0\u0906\0\u094c\0\u0992\0\106"+
    "\0\u09d8\0\106\0\106\0\u0a1e\0\106\0\u0a64\0\u0118\0\106"+
    "\0\106\0\106\0\u0aaa\0\u0af0\0\106\0\106\0\106\0\u0b36"+
    "\0\u0b7c\0\106\0\106\0\106\0\u0bc2\0\u0c08\0\u0c4e\0\u0c94"+
    "\0\u0cda\0\u0d20\0\u0d66\0\u0dac\0\u0df2\0\u0e38\0\u0e7e\0\u0ec4"+
    "\0\u0f0a\0\u0f50\0\u0f96\0\u0fdc\0\u1022\0\u1068\0\u10ae\0\u10f4"+
    "\0\u113a\0\u1180\0\u11c6\0\u120c\0\u1252\0\u1298\0\u12de\0\u1324"+
    "\0\u136a\0\u13b0\0\u13f6\0\u143c\0\u1482\0\u14c8\0\u1068\0\u150e"+
    "\0\u1554\0\106\0\106\0\106\0\106\0\u159a\0\u15e0\0\u1626"+
    "\0\u166c\0\u16b2\0\u16f8\0\u173e\0\u1784\0\u17ca\0\u1810\0\u1856"+
    "\0\u189c\0\u18e2\0\u1928\0\u196e\0\u19b4\0\u19fa\0\u1a40\0\u1a86"+
    "\0\u1acc\0\u1b12\0\u1b58\0\u1b9e\0\u1be4\0\u1c2a\0\u1c70\0\u1cb6"+
    "\0\u1cfc\0\u1d42\0\u1d88\0\u1dce\0\u1e14\0\u1e5a\0\u0532\0\u1ea0"+
    "\0\106\0\u1ee6\0\106\0\u1f2c\0\u1f72\0\u1fb8\0\u1ffe\0\u0532"+
    "\0\u2044\0\u208a\0\u20d0\0\u2116\0\u215c\0\u21a2\0\u21e8\0\u222e"+
    "\0\u2274\0\u0532\0\u22ba\0\u2300\0\u2346\0\u238c\0\u23d2\0\u0532"+
    "\0\u2418\0\u245e\0\u24a4\0\u24ea\0\u2530\0\u2576\0\u25bc\0\u2602"+
    "\0\u2648\0\u0532\0\u268e\0\u26d4\0\u271a\0\u2760\0\u27a6\0\u27ec"+
    "\0\u2832\0\u2878\0\u28be\0\u0532\0\u2904\0\u294a\0\u2990\0\u0532"+
    "\0\u0532\0\u0532\0\u29d6\0\u2a1c\0\u2a62\0\u2aa8\0\u2aee\0\u2b34"+
    "\0\u2b7a\0\u2bc0\0\u2c06\0\u0532\0\u2c4c\0\u2c92\0\u2cd8\0\u2d1e"+
    "\0\u2d64\0\u2daa\0\u2df0\0\u0532\0\u2e36\0\u2e7c\0\u2ec2\0\u2f08"+
    "\0\u0532\0\u2f4e\0\u2f94\0\u2fda\0\u3020\0\u3066\0\u0532\0\u0532"+
    "\0\u30ac\0\u0532\0\u30f2\0\u3138\0\u317e\0\u31c4\0\u0532\0\u320a"+
    "\0\u3250\0\u0532\0\u0532\0\u3296\0\u32dc\0\u3322\0\u0532\0\u0532"+
    "\0\u3368\0\u33ae\0\u0532\0\u33f4\0\u343a\0\u3480\0\u0532\0\106"+
    "\0\u34c6\0\u350c\0\106\0\u0532\0\u0532\0\u3552\0\u0532\0\u0532"+
    "\0\u0532\0\u3598\0\u35de\0\u3624\0\u366a\0\u0532\0\u0532\0\u36b0"+
    "\0\u0532\0\u0532";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[266];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\2\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\2\1\50\1\51\1\26\1\27\1\30\1\52\1\32"+
    "\1\53\1\34\1\35\2\34\1\54\1\55\1\41\1\34"+
    "\1\42\1\56\1\57\1\45\4\34\1\60\1\61\1\62"+
    "\107\0\3\3\106\0\1\63\3\0\1\64\15\0\1\65"+
    "\55\0\1\66\1\0\5\67\1\70\44\67\1\0\33\67"+
    "\10\0\1\71\73\0\1\72\1\0\6\73\1\74\2\73"+
    "\1\0\74\73\15\0\1\75\10\0\1\76\76\0\1\77"+
    "\106\0\1\100\1\0\1\20\102\0\1\101\6\0\1\102"+
    "\105\0\1\103\105\0\1\104\1\105\100\0\1\34\5\0"+
    "\21\34\4\0\17\34\1\106\6\34\25\0\1\34\5\0"+
    "\21\34\4\0\15\34\1\107\10\34\25\0\1\34\5\0"+
    "\21\34\4\0\1\110\7\34\1\111\4\34\1\112\10\34"+
    "\25\0\1\34\5\0\21\34\4\0\4\34\1\113\10\34"+
    "\1\114\10\34\25\0\1\34\5\0\21\34\4\0\14\34"+
    "\1\115\3\34\1\116\3\34\1\117\1\34\25\0\1\34"+
    "\5\0\21\34\4\0\1\120\25\34\25\0\1\34\5\0"+
    "\21\34\4\0\26\34\25\0\1\34\5\0\21\34\4\0"+
    "\1\121\25\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\122\21\34\25\0\1\34\5\0\21\34\4\0\10\34"+
    "\1\123\4\34\1\124\10\34\25\0\1\34\5\0\21\34"+
    "\4\0\4\34\1\125\3\34\1\126\15\34\25\0\1\34"+
    "\5\0\21\34\4\0\15\34\1\127\10\34\25\0\1\34"+
    "\5\0\21\34\4\0\1\130\7\34\1\131\6\34\1\132"+
    "\6\34\25\0\1\34\5\0\21\34\4\0\1\133\3\34"+
    "\1\134\21\34\25\0\1\34\5\0\21\34\4\0\1\135"+
    "\7\34\1\136\11\34\1\137\1\140\2\34\25\0\1\34"+
    "\5\0\21\34\4\0\17\34\1\141\6\34\25\0\1\34"+
    "\5\0\21\34\4\0\1\142\3\34\1\143\21\34\25\0"+
    "\1\34\5\0\21\34\4\0\4\34\1\113\10\34\1\144"+
    "\10\34\25\0\1\34\5\0\21\34\4\0\1\145\25\34"+
    "\25\0\1\34\5\0\21\34\4\0\1\146\7\34\1\123"+
    "\4\34\1\124\10\34\25\0\1\34\5\0\21\34\4\0"+
    "\4\34\1\125\3\34\1\147\15\34\25\0\1\34\5\0"+
    "\21\34\4\0\1\133\3\34\1\150\21\34\25\0\1\34"+
    "\5\0\21\34\4\0\1\135\7\34\1\136\4\34\1\151"+
    "\4\34\1\137\1\140\2\34\107\0\1\152\11\0\1\153"+
    "\201\0\1\154\12\0\1\155\74\0\11\73\1\155\74\73"+
    "\22\0\1\156\63\0\17\101\1\157\7\101\1\0\56\101"+
    "\2\105\1\0\103\105\22\0\1\34\5\0\21\34\4\0"+
    "\17\34\1\160\6\34\25\0\1\34\5\0\21\34\4\0"+
    "\15\34\1\161\10\34\25\0\1\34\5\0\21\34\4\0"+
    "\3\34\1\162\13\34\1\163\1\164\5\34\25\0\1\34"+
    "\5\0\21\34\4\0\17\34\1\165\6\34\25\0\1\34"+
    "\5\0\21\34\4\0\14\34\1\166\11\34\25\0\1\34"+
    "\5\0\21\34\4\0\5\34\1\167\20\34\25\0\1\34"+
    "\5\0\21\34\4\0\1\34\1\170\24\34\25\0\1\34"+
    "\5\0\21\34\4\0\21\34\1\171\4\34\25\0\1\34"+
    "\5\0\21\34\4\0\16\34\1\172\7\34\25\0\1\34"+
    "\5\0\21\34\4\0\21\34\1\173\4\34\25\0\1\34"+
    "\5\0\21\34\4\0\12\34\1\174\13\34\25\0\1\34"+
    "\5\0\21\34\4\0\2\34\1\175\23\34\25\0\1\34"+
    "\5\0\21\34\4\0\4\34\1\176\21\34\25\0\1\34"+
    "\5\0\21\34\4\0\20\34\1\177\5\34\25\0\1\34"+
    "\5\0\21\34\4\0\14\34\1\200\11\34\25\0\1\34"+
    "\5\0\21\34\4\0\14\34\1\201\11\34\25\0\1\34"+
    "\5\0\21\34\4\0\4\34\1\202\21\34\25\0\1\34"+
    "\5\0\21\34\4\0\13\34\1\203\12\34\25\0\1\34"+
    "\5\0\21\34\4\0\17\34\1\204\6\34\25\0\1\34"+
    "\5\0\21\34\4\0\20\34\1\205\5\34\25\0\1\34"+
    "\5\0\21\34\4\0\10\34\1\206\15\34\25\0\1\34"+
    "\5\0\21\34\4\0\14\34\1\207\11\34\25\0\1\34"+
    "\5\0\21\34\4\0\16\34\1\210\2\34\1\211\4\34"+
    "\25\0\1\34\5\0\21\34\4\0\12\34\1\212\13\34"+
    "\25\0\1\34\5\0\21\34\4\0\14\34\1\213\11\34"+
    "\25\0\1\34\5\0\21\34\4\0\13\34\1\214\12\34"+
    "\25\0\1\34\5\0\21\34\4\0\10\34\1\215\15\34"+
    "\25\0\1\34\5\0\21\34\4\0\22\34\1\216\3\34"+
    "\25\0\1\34\5\0\21\34\4\0\17\34\1\217\6\34"+
    "\25\0\1\34\5\0\21\34\4\0\17\34\1\220\6\34"+
    "\11\0\1\221\13\0\1\34\5\0\21\34\4\0\1\34"+
    "\1\170\24\34\11\0\1\221\13\0\1\34\5\0\21\34"+
    "\4\0\12\34\1\174\13\34\11\0\1\221\13\0\1\34"+
    "\5\0\21\34\4\0\26\34\11\0\1\221\13\0\1\34"+
    "\5\0\21\34\4\0\16\34\1\210\2\34\1\211\4\34"+
    "\25\0\1\34\5\0\21\34\4\0\12\34\1\146\13\34"+
    "\25\0\1\222\112\0\1\223\100\0\1\34\5\0\21\34"+
    "\4\0\4\34\1\224\21\34\25\0\1\34\5\0\21\34"+
    "\4\0\12\34\1\225\13\34\25\0\1\34\5\0\21\34"+
    "\4\0\4\34\1\226\21\34\25\0\1\34\5\0\21\34"+
    "\4\0\1\227\25\34\25\0\1\34\5\0\21\34\4\0"+
    "\15\34\1\230\10\34\25\0\1\34\5\0\21\34\4\0"+
    "\2\34\1\231\23\34\25\0\1\34\5\0\21\34\4\0"+
    "\21\34\1\232\4\34\25\0\1\34\5\0\21\34\4\0"+
    "\1\233\25\34\25\0\1\34\5\0\21\34\4\0\12\34"+
    "\1\234\13\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\235\21\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\236\21\34\25\0\1\34\5\0\21\34\4\0\10\34"+
    "\1\237\15\34\25\0\1\34\5\0\21\34\4\0\20\34"+
    "\1\240\5\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\241\21\34\25\0\1\34\5\0\21\34\4\0\16\34"+
    "\1\242\7\34\25\0\1\34\5\0\21\34\4\0\21\34"+
    "\1\243\4\34\25\0\1\34\5\0\21\34\4\0\6\34"+
    "\1\244\17\34\25\0\1\34\5\0\21\34\4\0\20\34"+
    "\1\245\5\34\25\0\1\34\5\0\21\34\4\0\14\34"+
    "\1\246\11\34\25\0\1\34\5\0\21\34\4\0\1\34"+
    "\1\247\24\34\25\0\1\34\5\0\21\34\4\0\1\250"+
    "\25\34\25\0\1\34\5\0\21\34\4\0\21\34\1\251"+
    "\4\34\25\0\1\34\5\0\21\34\4\0\14\34\1\252"+
    "\11\34\25\0\1\34\5\0\21\34\4\0\3\34\1\253"+
    "\22\34\25\0\1\34\5\0\21\34\4\0\17\34\1\254"+
    "\6\34\25\0\1\34\5\0\21\34\4\0\15\34\1\255"+
    "\10\34\25\0\1\34\5\0\21\34\4\0\10\34\1\256"+
    "\15\34\25\0\1\34\5\0\21\34\4\0\15\34\1\257"+
    "\10\34\25\0\1\34\5\0\21\34\4\0\1\260\25\34"+
    "\25\0\1\34\5\0\21\34\4\0\21\34\1\261\4\34"+
    "\25\0\1\34\5\0\21\34\4\0\4\34\1\262\21\34"+
    "\25\0\1\34\5\0\21\34\4\0\3\34\1\263\22\34"+
    "\25\0\1\264\105\0\1\34\5\0\21\34\4\0\6\34"+
    "\1\265\17\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\266\21\34\25\0\1\34\5\0\21\34\4\0\14\34"+
    "\1\267\11\34\25\0\1\34\5\0\21\34\4\0\2\34"+
    "\1\270\23\34\25\0\1\34\5\0\21\34\4\0\22\34"+
    "\1\271\3\34\25\0\1\34\5\0\21\34\4\0\10\34"+
    "\1\272\15\34\25\0\1\34\5\0\21\34\4\0\22\34"+
    "\1\273\3\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\274\21\34\25\0\1\34\5\0\21\34\4\0\17\34"+
    "\1\275\6\34\25\0\1\34\5\0\21\34\4\0\17\34"+
    "\1\276\6\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\277\21\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\300\10\34\1\300\10\34\25\0\1\34\5\0\21\34"+
    "\4\0\17\34\1\301\6\34\25\0\1\34\5\0\21\34"+
    "\4\0\1\302\25\34\25\0\1\34\5\0\21\34\4\0"+
    "\10\34\1\303\15\34\25\0\1\34\5\0\21\34\4\0"+
    "\1\304\25\34\25\0\1\34\5\0\21\34\4\0\21\34"+
    "\1\305\4\34\25\0\1\34\5\0\21\34\4\0\17\34"+
    "\1\306\6\34\25\0\1\34\5\0\21\34\4\0\1\307"+
    "\25\34\25\0\1\34\5\0\21\34\4\0\2\34\1\310"+
    "\23\34\25\0\1\34\5\0\21\34\4\0\15\34\1\311"+
    "\10\34\25\0\1\34\5\0\21\34\4\0\15\34\1\312"+
    "\10\34\25\0\1\34\5\0\21\34\4\0\17\34\1\313"+
    "\6\34\25\0\1\34\5\0\21\34\4\0\17\34\1\314"+
    "\6\34\6\0\1\315\16\0\1\34\5\0\21\34\4\0"+
    "\26\34\25\0\1\34\5\0\21\34\4\0\17\34\1\316"+
    "\6\34\25\0\1\34\5\0\21\34\4\0\2\34\1\317"+
    "\23\34\25\0\1\34\5\0\21\34\4\0\1\320\25\34"+
    "\25\0\1\321\105\0\1\34\5\0\21\34\4\0\12\34"+
    "\1\322\13\34\25\0\1\34\5\0\21\34\4\0\1\323"+
    "\25\34\25\0\1\34\5\0\21\34\4\0\1\324\25\34"+
    "\25\0\1\34\5\0\21\34\4\0\21\34\1\325\4\34"+
    "\25\0\1\34\5\0\21\34\4\0\12\34\1\326\13\34"+
    "\25\0\1\34\5\0\21\34\4\0\14\34\1\327\11\34"+
    "\25\0\1\34\5\0\21\34\4\0\12\34\1\330\13\34"+
    "\25\0\1\34\5\0\21\34\4\0\15\34\1\331\10\34"+
    "\25\0\1\34\5\0\21\34\4\0\1\332\25\34\25\0"+
    "\1\34\5\0\21\34\4\0\14\34\1\333\11\34\25\0"+
    "\1\34\5\0\21\34\4\0\21\34\1\334\4\34\25\0"+
    "\1\34\5\0\21\34\4\0\11\34\1\335\14\34\25\0"+
    "\1\34\5\0\21\34\4\0\17\34\1\336\6\34\25\0"+
    "\1\34\5\0\21\34\4\0\4\34\1\337\21\34\25\0"+
    "\1\34\5\0\21\34\4\0\20\34\1\340\5\34\25\0"+
    "\1\34\5\0\21\34\4\0\10\34\1\341\15\34\25\0"+
    "\1\34\5\0\21\34\4\0\13\34\1\342\12\34\25\0"+
    "\1\34\5\0\21\34\4\0\3\34\1\343\22\34\25\0"+
    "\1\34\5\0\21\34\4\0\14\34\1\344\11\34\100\0"+
    "\1\345\32\0\1\34\5\0\21\34\4\0\10\34\1\346"+
    "\15\34\25\0\1\34\5\0\21\34\4\0\7\34\1\347"+
    "\16\34\25\0\1\34\5\0\21\34\4\0\3\34\1\350"+
    "\22\34\25\0\1\351\105\0\1\34\5\0\21\34\4\0"+
    "\15\34\1\352\10\34\25\0\1\34\5\0\21\34\4\0"+
    "\14\34\1\353\11\34\25\0\1\34\5\0\21\34\4\0"+
    "\4\34\1\354\21\34\25\0\1\34\5\0\21\34\4\0"+
    "\1\355\25\34\25\0\1\34\5\0\21\34\4\0\22\34"+
    "\1\356\3\34\25\0\1\34\5\0\21\34\4\0\21\34"+
    "\1\357\4\34\25\0\1\34\5\0\21\34\4\0\17\34"+
    "\1\360\6\34\25\0\1\34\5\0\21\34\4\0\3\34"+
    "\1\361\22\34\25\0\1\34\5\0\21\34\4\0\22\34"+
    "\1\362\3\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\363\21\34\25\0\1\34\5\0\21\34\4\0\1\364"+
    "\25\34\25\0\1\34\5\0\21\34\4\0\16\34\1\365"+
    "\7\34\25\0\1\34\5\0\21\34\4\0\22\34\1\366"+
    "\3\34\25\0\1\34\5\0\21\34\4\0\1\367\25\34"+
    "\70\0\1\370\42\0\1\34\5\0\21\34\4\0\25\34"+
    "\1\371\25\0\1\34\5\0\21\34\4\0\4\34\1\372"+
    "\21\34\25\0\1\373\105\0\1\34\5\0\21\34\4\0"+
    "\17\34\1\374\6\34\25\0\1\34\5\0\21\34\4\0"+
    "\17\34\1\375\6\34\25\0\1\34\5\0\21\34\4\0"+
    "\1\376\25\34\25\0\1\34\5\0\21\34\4\0\4\34"+
    "\1\377\21\34\25\0\1\34\5\0\21\34\4\0\3\34"+
    "\1\u0100\22\34\25\0\1\34\5\0\21\34\4\0\20\34"+
    "\1\u0101\5\34\25\0\1\34\5\0\21\34\4\0\1\u0102"+
    "\25\34\25\0\1\34\5\0\21\34\4\0\2\34\1\u0103"+
    "\23\34\25\0\1\34\5\0\21\34\4\0\1\u0104\25\34"+
    "\25\0\1\34\5\0\21\34\4\0\17\34\1\u0105\6\34"+
    "\25\0\1\34\5\0\21\34\4\0\17\34\1\u0106\6\34"+
    "\25\0\1\34\5\0\21\34\4\0\12\34\1\u0107\13\34"+
    "\25\0\1\34\5\0\21\34\4\0\10\34\1\u0108\15\34"+
    "\25\0\1\34\5\0\21\34\4\0\17\34\1\u0109\6\34"+
    "\25\0\1\34\5\0\21\34\4\0\15\34\1\262\10\34"+
    "\25\0\1\34\5\0\21\34\4\0\17\34\1\u010a\6\34"+
    "\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14070];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\3\11\1\1\1\11"+
    "\1\1\1\11\1\1\2\11\24\1\3\11\6\1\1\11"+
    "\1\1\2\11\1\0\1\11\2\0\3\11\2\0\3\11"+
    "\2\0\3\11\45\1\4\11\1\1\1\0\41\1\1\11"+
    "\1\1\1\11\71\1\1\0\27\1\1\0\22\1\1\11"+
    "\2\1\1\11\17\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[266];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private List<ErrorCom> erroresCom;
    private int identCant;
    private boolean identar;

    private void error(String lexeme) {
        erroresCom.add(new ErrorCom("Lexico","Simbolo no existe en el lenguaje",String.valueOf(yyline+1),String.valueOf(yycolumn+1),lexeme));
    }    

    private void errorPrueba(String lexeme, String tipo) {
        erroresCom.add(new ErrorCom("PRUEBA",tipo,String.valueOf(yyline+1),String.valueOf(yycolumn+1),lexeme));
    }

    public List<ErrorCom> getErroresCom() {
        return erroresCom;
    }

    private int verificarIdentacion(String valor){
        for(char c : valor.toCharArray()) {
            if(c == '\n'){
                this.identCant = 0;
                identar = true;
            } else if (c == ' ' || c == 32) {
                this.identCant++;
            } else if (c == '\t') {
                this.identCant += 4;
            } else {
                identar = false;
            }
        } 
        if(identar == true && this.identCant != 0){
            int cantidadIdent = 0;
            while(this.identCant >= 4){
                cantidadIdent++;
                this.identCant = this.identCant - 4; 
            }
            this.identCant = 0;
            return cantidadIdent;
        }
        return -1;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCompilar(java.io.Reader in) {
      erroresCom = new ArrayList<>();
    identar = true;
    identCant = 0;
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error(yytext()); new Symbol(sym.error,yyline,yycolumn, yytext());
            }
            // fall through
          case 76: break;
          case 2:
            { int val = verificarIdentacion(yytext()); if(val >= 1){return new Symbol(sym.IDENT,yyline+1,yycolumn+1, String.valueOf(val));}
            }
            // fall through
          case 77: break;
          case 3:
            { verificarIdentacion(yytext());return new Symbol(sym.OPNOT,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 78: break;
          case 4:
            { verificarIdentacion(yytext());return new Symbol(sym.OPMOD,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 79: break;
          case 5:
            { verificarIdentacion(yytext());return new Symbol(sym.PARI,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 80: break;
          case 6:
            { verificarIdentacion(yytext());return new Symbol(sym.PARD,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 81: break;
          case 7:
            { verificarIdentacion(yytext());return new Symbol(sym.MULT,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 82: break;
          case 8:
            { verificarIdentacion(yytext());return new Symbol(sym.SUMA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 83: break;
          case 9:
            { verificarIdentacion(yytext());return new Symbol(sym.COMA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 84: break;
          case 10:
            { verificarIdentacion(yytext());return new Symbol(sym.RESTA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 85: break;
          case 11:
            { verificarIdentacion(yytext());return new Symbol(sym.DIVI,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 86: break;
          case 12:
            { verificarIdentacion(yytext());return new Symbol(sym.NUMERO,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 87: break;
          case 13:
            { verificarIdentacion(yytext());return new Symbol(sym.DOSPUNT,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 88: break;
          case 14:
            { verificarIdentacion(yytext());return new Symbol(sym.PUNTCOMA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 89: break;
          case 15:
            { verificarIdentacion(yytext());return new Symbol(sym.MEN,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 90: break;
          case 16:
            { verificarIdentacion(yytext());return new Symbol(sym.IGUAL,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 91: break;
          case 17:
            { verificarIdentacion(yytext());return new Symbol(sym.MAY,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 92: break;
          case 18:
            { verificarIdentacion(yytext());return new Symbol(sym.ID,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 93: break;
          case 19:
            { verificarIdentacion(yytext());return new Symbol(sym.BRACKI,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 94: break;
          case 20:
            { verificarIdentacion(yytext());return new Symbol(sym.BRACKD,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 95: break;
          case 21:
            { verificarIdentacion(yytext());return new Symbol(sym.OPELV,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 96: break;
          case 22:
            { verificarIdentacion(yytext());return new Symbol(sym.CURLBRACKI,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 97: break;
          case 23:
            { verificarIdentacion(yytext());return new Symbol(sym.CURLBRACKD,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 98: break;
          case 24:
            { verificarIdentacion(yytext());return new Symbol(sym.OPNULO,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 99: break;
          case 25:
            { verificarIdentacion(yytext());return new Symbol(sym.DIFERENC,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 100: break;
          case 26:
            { verificarIdentacion(yytext());return new Symbol(sym.CADENA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 101: break;
          case 27:
            { verificarIdentacion(yytext());return new Symbol(sym.AND,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 102: break;
          case 28:
            { verificarIdentacion(yytext());return new Symbol(sym.XOR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 103: break;
          case 29:
            { verificarIdentacion(yytext());return new Symbol(sym.OPINCR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 104: break;
          case 30:
            { verificarIdentacion(yytext());return new Symbol(sym.OPSUMSIM,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 105: break;
          case 31:
            { verificarIdentacion(yytext());return new Symbol(sym.OPDECR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 106: break;
          case 32:
            { verificarIdentacion(yytext());return new Symbol(sym.MENIG,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 107: break;
          case 33:
            { verificarIdentacion(yytext());return new Symbol(sym.DOBIGUAL,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 108: break;
          case 34:
            { verificarIdentacion(yytext());return new Symbol(sym.MAYIG,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 109: break;
          case 35:
            { verificarIdentacion(yytext());return new Symbol(sym.COMENT,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 110: break;
          case 36:
            { verificarIdentacion(yytext());return new Symbol(sym.SI,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 111: break;
          case 37:
            { verificarIdentacion(yytext());return new Symbol(sym.NOTA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 112: break;
          case 38:
            { verificarIdentacion(yytext());return new Symbol(sym.OR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 113: break;
          case 39:
            { verificarIdentacion(yytext());return new Symbol(sym.NAND,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 114: break;
          case 40:
            { verificarIdentacion(yytext());return new Symbol(sym.NOR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 115: break;
          case 41:
            { verificarIdentacion(yytext());return new Symbol(sym.CARACTER,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 116: break;
          case 42:
            { verificarIdentacion(yytext());return new Symbol(sym.VAR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 117: break;
          case 43:
            { verificarIdentacion(yytext());return new Symbol(sym.CASO,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 118: break;
          case 44:
            { verificarIdentacion(yytext());return new Symbol(sym.KEEP,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 119: break;
          case 45:
            { verificarIdentacion(yytext());return new Symbol(sym.PARA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 120: break;
          case 46:
            { verificarIdentacion(yytext());return new Symbol(sym.SINO,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 121: break;
          case 47:
            { verificarIdentacion(yytext());return new Symbol(sym.VERDADERO,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 122: break;
          case 48:
            { verificarIdentacion(yytext());return new Symbol(sym.DOBLESTR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 123: break;
          case 49:
            { verificarIdentacion(yytext());return new Symbol(sym.FALSO,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 124: break;
          case 50:
            { verificarIdentacion(yytext());return new Symbol(sym.HACER,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 125: break;
          case 51:
            { verificarIdentacion(yytext());return new Symbol(sym.LISTA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 126: break;
          case 52:
            { verificarIdentacion(yytext());return new Symbol(sym.PISTA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 127: break;
          case 53:
            { verificarIdentacion(yytext());return new Symbol(sym.SALIR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 128: break;
          case 54:
            { verificarIdentacion(yytext());return new Symbol(sym.CADENASTR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 129: break;
          case 55:
            { verificarIdentacion(yytext());return new Symbol(sym.ENTEROSTR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 130: break;
          case 56:
            { verificarIdentacion(yytext());return new Symbol(sym.NOMBRE,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 131: break;
          case 57:
            { verificarIdentacion(yytext());return new Symbol(sym.PISTAS,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 132: break;
          case 58:
            { verificarIdentacion(yytext());return new Symbol(sym.RANDOM,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 133: break;
          case 59:
            { verificarIdentacion(yytext());return new Symbol(sym.SWITCH,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 134: break;
          case 60:
            { verificarIdentacion(yytext());return new Symbol(sym.ARREGLO,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 135: break;
          case 61:
            { verificarIdentacion(yytext());return new Symbol(sym.BOOLEANSTR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 136: break;
          case 62:
            { verificarIdentacion(yytext());return new Symbol(sym.DEFAULT,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 137: break;
          case 63:
            { verificarIdentacion(yytext());return new Symbol(sym.ESPERAR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 138: break;
          case 64:
            { verificarIdentacion(yytext());return new Symbol(sym.MENSAJE,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 139: break;
          case 65:
            { verificarIdentacion(yytext());return new Symbol(sym.RETORNA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 140: break;
          case 66:
            { verificarIdentacion(yytext());return new Symbol(sym.SINOSI,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 141: break;
          case 67:
            { verificarIdentacion(yytext());return new Symbol(sym.CARACTERSTR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 142: break;
          case 68:
            { verificarIdentacion(yytext());return new Symbol(sym.CIRCULAR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 143: break;
          case 69:
            { verificarIdentacion(yytext());return new Symbol(sym.EXTIENDE,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 144: break;
          case 70:
            { verificarIdentacion(yytext());return new Symbol(sym.LONGITUD,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 145: break;
          case 71:
            { verificarIdentacion(yytext());return new Symbol(sym.MIENTRAS,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 146: break;
          case 72:
            { verificarIdentacion(yytext());return new Symbol(sym.CONTINUAR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 147: break;
          case 73:
            { verificarIdentacion(yytext());return new Symbol(sym.PRINCIPAL,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 148: break;
          case 74:
            { verificarIdentacion(yytext());return new Symbol(sym.SUMARIZAR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 149: break;
          case 75:
            { verificarIdentacion(yytext());return new Symbol(sym.REPRODUCIR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 150: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java LexerCompilar [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        LexerCompilar scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new LexerCompilar(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
